title: Kaleidoscope
site:
  description: "Everything about Kaleidoscope, a firmware for computer input devices"
  url: "http://kaleidoscope.5ms.in"
  base_url: "/"
  repository: "algernon/Kaleidoscope-Website"
#  og_image: ...
permalink: /:categories/:title
breadcrumbs: true
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.16.0"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
# comments:
#   provider: "discourse"
#   discourse:
#     server: community.keyboard.io
twitter:
  username: keyboardio
social:
  type: Organization
  links:
    - "https://twitter.com/keyboardio"
    - "https://github.com/keyboardio"
    - "http://kaleidoscope.5ms.in/"
author:
  name: "Keyboardio"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/keyboardio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/keyboardio"
    - label: "Shop"
      icon: "fab fa-fw fa-link"
      url: "https://shop.keyboard.io/"
